#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Dict, Optional

import numpy as np


@dataclass(frozen=True)
class PartArtifacts:
    mesh: str
    frame: str
    physics: str

    @property
    def visual(self) -> str:
        return self.mesh

    @property
    def collision(self) -> str:
        return self.mesh


def write_json(path: str, payload: Dict[str, object]) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def compute_face_normals(vertices: np.ndarray, faces: np.ndarray) -> np.ndarray:
    triangles = vertices[faces]
    normals = np.cross(triangles[:, 1] - triangles[:, 0], triangles[:, 2] - triangles[:, 0])
    normal_lengths = np.linalg.norm(normals, axis=1)
    valid = normal_lengths >= 1e-12
    normals[valid] /= normal_lengths[valid, None]
    normals[~valid] = np.array([0.0, 0.0, 1.0], dtype=float)
    return normals


def write_obj(path: str, vertices: np.ndarray, faces: np.ndarray, normals: Optional[np.ndarray] = None) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    vertex_lines = "".join(f"v {x:.9f} {y:.9f} {z:.9f}\n" for x, y, z in vertices)
    indexed_faces = faces + 1

    with open(path, "w", encoding="utf-8") as f:
        f.write("# generated by parts/common.py\n")
        if normals is not None:
            normal_lines = "".join(f"vn {nx:.9f} {ny:.9f} {nz:.9f}\n" for nx, ny, nz in normals)
            face_lines = "".join(
                f"f {a}//{index} {b}//{index} {c}//{index}\n" for index, (a, b, c) in enumerate(indexed_faces, start=1)
            )
            f.write("s off\n")
            f.write(vertex_lines)
            f.write(normal_lines)
            f.write(face_lines)
            return

        face_lines = "".join(f"f {a} {b} {c}\n" for a, b, c in indexed_faces)
        f.write(vertex_lines)
        f.write(face_lines)
